### ISSUE TITLE
Trying to deploy 4.15 and bootstrap node installs with older 4.6.12 release image  (io.openshift.release=4.6.12), my mistake.

### ISSUE THREAD

**Issue by whowutwut** [redhat-cop/ocp4-helpernode#319]
Hi All  👋 

I haven't deployed using this helpernode in some time and just started playing with it again.  I'm on a RHEL8 helper node running this playbook against bare metal servers.  I am able to install the bootstrap but having all sorts of issues getting it green ... 

I did make a mistake in that I mis-typed and was using a 4.6.12 installer when trying to deploy 4.16.  🫠  ...  

```diff
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.16/4.16.0/rhcos-4.16.0-x86_64-live-rootfs.x86_64.img"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.0/rhcos-4.16.0-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.0/rhcos-4.16.0-x86_64-live-kernel-x86_64"
+ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.12/openshift-client-linux-4.6.12.tar.gz"
+ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.12/openshift-install-linux-4.6.12.tar.gz"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.16.0/openshift-client-linux-4.16.0.tar.gz"
```

But I did have the ocp_client redefined below at 4.16.0... so maybe it was just the installer that was messed up.  OOPS...  I've since corrected that and re-created all the files again from scratch (or at least I think I did)... but somehow it's still remembering this 4.6.12 ...

When the bootstrap node gets installed, the `openshift-release-dev` is really old, 3 years back! 

```
[core@bootstrap ~]$ sudo podman images
REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
quay.io/openshift-release-dev/ocp-release  <none>      f3d6836533a7  3 years ago  320 MB
```

and I am seeing a bunch of logs like this where 4.6.12 is mentioned... `io.openshift.release=4.6.12`. . 

`Jul 10 15:36:13 bootstrap.ocp4-c83f2.example.com podman[22793]: 2024-07-10 15:36:13.349971741 +0000 UTC m=+0.041818282 container remove 3295e9ece70899120418f2bfb0356aed4fe4be6590f9fb1427780dee6a8e4750 (image=quay.io/openshift-release-dev/ocp-release@sha256:5c3618ab914eb66267b7c552a9b51c3018c3a8f8acf08ce1ff7ae4bfdd3a82bd, name=distracted_haibt, io.openshift.release=4.6.12, io.openshift.release.base-image-digest=sha256:ad175c14ca0a1d7a0d63044588f34da02122d412134d239cfaf1f44016b2dcd0)`

So it keeps having errors, current one is this: 

```
Jul 10 15:32:38 bootstrap.ocp4-c83f2.example.com vigorous_moore[9965]: F0710 15:32:38.994596       1 image.go:32] error: error: Unknown name requested, could not find cluster-config-api in UpdatePayload
Jul 10 15:32:38 bootstrap.ocp4-c83f2.example.com vigorous_moore[9965]: goroutine 1 [running]:
Jul 10 15:32:38 bootstrap.ocp4-c83f2.example.com bootkube.sh[9933]: F0710 15:32:38.994596       1 image.go:32] error: error: Unknown name requested, could not find cluster-config-api in UpdatePayload
...
```

What I'm using now, is 4.15 files... 

```bash
# 4.15
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.15/4.15.0/rhcos-4.15.0-x86_64-live-rootfs.x86_64.img"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.15/4.15.0/rhcos-4.15.0-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.15/4.15.0/rhcos-4.15.0-x86_64-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.15.0/openshift-client-linux-4.15.0.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.15.0/openshift-install-linux-4.15.0.tar.gz"
```

bootstrap node is installed at the 4.15 level 
![image](https://github.com/redhat-cop/ocp4-helpernode/assets/10049070/cd50b97a-0f37-4865-aa8d-c5561bf6cc61)

I tried to clean up all the directories and files that gets created by the playbook manually and all the ssh keys and everything, new ignition files, etc etc...  but I can't find anything left over...    the installer seems to be all at 4.15.. 

```
# sum openshift-install-linux-4.15.0.tar.gz
12713 428857
# sum /usr/local/src/openshift-install-linux.tar.gz
12713 428857
# openshift-install version
openshift-install 4.15.0
built from commit e8c70b7db9e64cafa7fe3182c365257c3e53fbb6
release image quay.io/openshift-release-dev/ocp-release@sha256:0da6316466d60a3a4535d5fed3589feb0391989982fba59d47d4c729912d6363
release architecture amd64
```

Does anyone out there know where it could be pulling this 4.6.12 from?  Should I just re-install the helper node?

**Comment by whowutwut** [comment]
I think I found it... 

```
[root@c83f2u02 ocp4]# openshift-install create manifests
INFO Consuming Install Config from target directory
INFO Manifests created in: manifests and openshift

[root@c83f2u02 ocp4]# grep -R 4.6 *
manifests/cvo-overrides.yaml:  channel: stable-4.6
openshift/openshift-install-manifests.yaml:  version: v4.6.0
```

Ah.. ok so there's some hidden files in the ocp4 directory...  and creating a new `~/ocp4` directory and running it resolves this... ! 

```
[root@c83f2u02 ~]# mv ocp4 ocp4.old
[root@c83f2u02 ~]# mkdir ocp4
[root@c83f2u02 ~]# cd ocp4
[root@c83f2u02 ocp4]# /usr/local/bin/openshift-install create manifests
INFO Consuming Install Config from target directory
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings
INFO Manifests created in: manifests and openshift
[root@c83f2u02 ocp4]# grep -R 4.15 *
manifests/cvo-overrides.yaml:  channel: stable-4.15
openshift/openshift-install-manifests.yaml:  version: v4.15.0
```
